[[libopenjpegextra]]
arch = "aarch64"
git-tree-sha1 = "688e46ac46ec96e6ec466073bbd586af3c54317d"
os = "macos"

    [[libopenjpegextra.download]]
    sha256 = "86112fa247a23ef924ed029448b7789db325f9dc80c59fc6752af25f4d1fb055"
    url = "https://github.com/JuliaBinaryWrappers/libopenjpegextra_jll.jl/releases/download/libopenjpegextra-v0.0.1+0/libopenjpegextra.v0.0.1.aarch64-apple-darwin.tar.gz"
[[libopenjpegextra]]
arch = "aarch64"
git-tree-sha1 = "bf9f4c920c77dbba2a13bf3a33e5faae1baffa8d"
libc = "glibc"
os = "linux"

    [[libopenjpegextra.download]]
    sha256 = "4304caa6d7ea2277fb7cbd2d2562d8dcc15c4e9c2a9038f4c756b73fbac0fdc4"
    url = "https://github.com/JuliaBinaryWrappers/libopenjpegextra_jll.jl/releases/download/libopenjpegextra-v0.0.1+0/libopenjpegextra.v0.0.1.aarch64-linux-gnu.tar.gz"
[[libopenjpegextra]]
arch = "aarch64"
git-tree-sha1 = "1dcf00ae554a10e326646c7d372192a3f49920de"
libc = "musl"
os = "linux"

    [[libopenjpegextra.download]]
    sha256 = "c2c18d16b17444efb2f31bd63d2ad92b1a42f2376050cbcc31a437837c11e375"
    url = "https://github.com/JuliaBinaryWrappers/libopenjpegextra_jll.jl/releases/download/libopenjpegextra-v0.0.1+0/libopenjpegextra.v0.0.1.aarch64-linux-musl.tar.gz"
[[libopenjpegextra]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5ccf02f71e5780a8d5bda38030447b428a842c7d"
libc = "glibc"
os = "linux"

    [[libopenjpegextra.download]]
    sha256 = "5717ced6b30543e6f47e8fd5a920deabe468f4f20629090d63507e6f3e0c12cc"
    url = "https://github.com/JuliaBinaryWrappers/libopenjpegextra_jll.jl/releases/download/libopenjpegextra-v0.0.1+0/libopenjpegextra.v0.0.1.armv6l-linux-gnueabihf.tar.gz"
[[libopenjpegextra]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0ad37fdfb2a08e524c67c0b20fce79b29c500f61"
libc = "musl"
os = "linux"

    [[libopenjpegextra.download]]
    sha256 = "b5aa4d7730e13ef57ef7863a1e1df8b97c1739f80a0bb89a8a3c9279fb2bf7c4"
    url = "https://github.com/JuliaBinaryWrappers/libopenjpegextra_jll.jl/releases/download/libopenjpegextra-v0.0.1+0/libopenjpegextra.v0.0.1.armv6l-linux-musleabihf.tar.gz"
[[libopenjpegextra]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2c9eee7507b71b3f5a03b14fa836f301e52bb0b9"
libc = "glibc"
os = "linux"

    [[libopenjpegextra.download]]
    sha256 = "f499b382e110c0de2c76d62b9795e1fc52bde8f907f468e4833d7e77b8038e29"
    url = "https://github.com/JuliaBinaryWrappers/libopenjpegextra_jll.jl/releases/download/libopenjpegextra-v0.0.1+0/libopenjpegextra.v0.0.1.armv7l-linux-gnueabihf.tar.gz"
[[libopenjpegextra]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bbc21b4e3cf5c98a1ecec0b9b1543bda5d324cb3"
libc = "musl"
os = "linux"

    [[libopenjpegextra.download]]
    sha256 = "dd319934850154d5978498e6406564190ccb10c9d8432ede421f39a33b95c481"
    url = "https://github.com/JuliaBinaryWrappers/libopenjpegextra_jll.jl/releases/download/libopenjpegextra-v0.0.1+0/libopenjpegextra.v0.0.1.armv7l-linux-musleabihf.tar.gz"
[[libopenjpegextra]]
arch = "i686"
git-tree-sha1 = "152d94ee71ad940c911ad7b0473bdac1bd7b0b50"
libc = "glibc"
os = "linux"

    [[libopenjpegextra.download]]
    sha256 = "08936af2b4a59e6bb0f73a95fde885d9a65c88c0cce61d6527a27d8ecaa0ba33"
    url = "https://github.com/JuliaBinaryWrappers/libopenjpegextra_jll.jl/releases/download/libopenjpegextra-v0.0.1+0/libopenjpegextra.v0.0.1.i686-linux-gnu.tar.gz"
[[libopenjpegextra]]
arch = "i686"
git-tree-sha1 = "f653e12b970bbf3af99b22e3c02abc5b8b03e914"
libc = "musl"
os = "linux"

    [[libopenjpegextra.download]]
    sha256 = "69ec87837e3b19b633f8d899997f7c679ab1025c41844030a7c7ff3cff02fef6"
    url = "https://github.com/JuliaBinaryWrappers/libopenjpegextra_jll.jl/releases/download/libopenjpegextra-v0.0.1+0/libopenjpegextra.v0.0.1.i686-linux-musl.tar.gz"
[[libopenjpegextra]]
arch = "i686"
git-tree-sha1 = "b2003883ba97b5ec128fd5c3646e4677e3034e2a"
os = "windows"

    [[libopenjpegextra.download]]
    sha256 = "72b60b0c88478374072c1f6c033c1b45485e3a3d69ad46843ddd41867e5a1fdc"
    url = "https://github.com/JuliaBinaryWrappers/libopenjpegextra_jll.jl/releases/download/libopenjpegextra-v0.0.1+0/libopenjpegextra.v0.0.1.i686-w64-mingw32.tar.gz"
[[libopenjpegextra]]
arch = "powerpc64le"
git-tree-sha1 = "78b90d313c4128c37d3c388b40cb51024057afc4"
libc = "glibc"
os = "linux"

    [[libopenjpegextra.download]]
    sha256 = "5bee1decf62ad4337424210410c2b946917ed6035057e2e4c0e6e22417189b89"
    url = "https://github.com/JuliaBinaryWrappers/libopenjpegextra_jll.jl/releases/download/libopenjpegextra-v0.0.1+0/libopenjpegextra.v0.0.1.powerpc64le-linux-gnu.tar.gz"
[[libopenjpegextra]]
arch = "x86_64"
git-tree-sha1 = "1ddc03bd3a9b0edd8bc3191648fb23671aae21b6"
os = "macos"

    [[libopenjpegextra.download]]
    sha256 = "93837dca6f15a4056dc10b1c578a0900a07f66cf43b4c84dedec1af2a7ad2133"
    url = "https://github.com/JuliaBinaryWrappers/libopenjpegextra_jll.jl/releases/download/libopenjpegextra-v0.0.1+0/libopenjpegextra.v0.0.1.x86_64-apple-darwin.tar.gz"
[[libopenjpegextra]]
arch = "x86_64"
git-tree-sha1 = "bdb5054caae6763a0a4a548a4be999c974c6495a"
libc = "glibc"
os = "linux"

    [[libopenjpegextra.download]]
    sha256 = "5f1978e573494151d7b9b5188f9faead45ba8e17bffabedcc69a9d36d57d1b0a"
    url = "https://github.com/JuliaBinaryWrappers/libopenjpegextra_jll.jl/releases/download/libopenjpegextra-v0.0.1+0/libopenjpegextra.v0.0.1.x86_64-linux-gnu.tar.gz"
[[libopenjpegextra]]
arch = "x86_64"
git-tree-sha1 = "9615cdf022f3b54809f76227c9840fd4533dd6a5"
libc = "musl"
os = "linux"

    [[libopenjpegextra.download]]
    sha256 = "f8e5d9aed3e1697781e1713b66cb5b5da548bf4039680eb48a0b9c6aa701dd4f"
    url = "https://github.com/JuliaBinaryWrappers/libopenjpegextra_jll.jl/releases/download/libopenjpegextra-v0.0.1+0/libopenjpegextra.v0.0.1.x86_64-linux-musl.tar.gz"
[[libopenjpegextra]]
arch = "x86_64"
git-tree-sha1 = "6284becaf5f19ed7d8c0cdbba03b411e7e57b2d7"
os = "freebsd"

    [[libopenjpegextra.download]]
    sha256 = "4fda83c4629faabee21cf57c78ba96df541bdd98a4b81293c8d271d960ef41d6"
    url = "https://github.com/JuliaBinaryWrappers/libopenjpegextra_jll.jl/releases/download/libopenjpegextra-v0.0.1+0/libopenjpegextra.v0.0.1.x86_64-unknown-freebsd.tar.gz"
[[libopenjpegextra]]
arch = "x86_64"
git-tree-sha1 = "249c1e11009762e4ba000513d06e172aa47eb2e7"
os = "windows"

    [[libopenjpegextra.download]]
    sha256 = "6bad92381f85824104e458ae8c63d07e62f11ccd45b9d1952a5f807ae44f4cc4"
    url = "https://github.com/JuliaBinaryWrappers/libopenjpegextra_jll.jl/releases/download/libopenjpegextra-v0.0.1+0/libopenjpegextra.v0.0.1.x86_64-w64-mingw32.tar.gz"
