# Autogenerated wrapper script for libopenjpegextra_jll for aarch64-apple-darwin
export libopenjpegextra

using OpenJpeg_jll
JLLWrappers.@generate_wrapper_header("libopenjpegextra")
JLLWrappers.@declare_library_product(libopenjpegextra, "@rpath/libopenjpegextra.dylib")
function __init__()
    JLLWrappers.@generate_init_header(OpenJpeg_jll)
    JLLWrappers.@init_library_product(
        libopenjpegextra,
        "lib/libopenjpegextra.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
