# Autogenerated wrapper script for libopenjpegextra_jll for i686-w64-mingw32
export libopenjpegextra

using OpenJpeg_jll
JLLWrappers.@generate_wrapper_header("libopenjpegextra")
JLLWrappers.@declare_library_product(libopenjpegextra, "libopenjpegextra.dll")
function __init__()
    JLLWrappers.@generate_init_header(OpenJpeg_jll)
    JLLWrappers.@init_library_product(
        libopenjpegextra,
        "bin\\libopenjpegextra.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
